### ISSUE TITLE
on Zoom Changed -> Refresh Map

### ISSUE THREAD

**Issue by ralexrdz** [PolymerVis/mapbox-gl#11]
I have a Polymer element where I have this 3 properties: `mapCenterLat`, `mapCenterLong` and `mapZoom`

I can't not reproduce the same behavior I see when binding on the  `<mapbox-gl>` element  the attribute `latitude` and `longitude`, on the `zoom` attribute.

I would like to refresh the map the same way is refreshed when I change my varialbes of Lat and Long that are linked to the mapbox-gl element, when updating my variable mapZoom.

I added to your code an observer to the zoom variable
``` js
zoom: {
            type: Number,
            notify: true,
            value: 11,
            observer: '_zoomChanged'
          },
```
``` js
_zoomChanged (zoom) {
        if (!this.map ) return
        this.map.transform.zoom = zoom
        this.map._update()
      }
```
this does the trick, but labels of streets on map don't update correcly.

Any suggestion?

**Comment by eterna2** [comment]
You need to debounce, instead of updating directly because a lot of the internal states are interconnected, and will trigger each other. 

Anyway, I have updated `zoom` to be data-bindable for v2.0.6. Just update and it should work now.

You can see the demo @ https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/databind.html
