### ISSUE TITLE
Point Layer not rendering

### ISSUE THREAD

**Issue by jparish3** [PolymerVis/mapbox-gl#12]
This is the only layer from examples that does not seem to work. I might be missing something
From examples:
<mapbox-layer
  map="[[map]]"
  layer-id="layer_points"
  rendering-type="circle"
  source-data="[[geojson]]"
  color="#009688"
  opacity=0.7></mapbox-layer>

**Comment by eterna2** [comment]
sorry can u tell me which example specifically?

Actually I have not fully implemented all the layers available in mapbox-gl. But all the examples should work. You can look at the demos, as I may have some typos in the examples.

**Comment by jparish3** [comment]
In the <mapbox-layer> 2nd example under the heading below. Since posting, I
have been able to render in conjunction with the <heatmap-layer> (not sure
why) using the same data source. I was hoping to display circles for
data-driven styling (using stops). Anyhow, I think this one of the best web
components in the entire library...please keep evolving it. Thanks


*Specify at source-data*






Joe Parish
Managing Partner
SPATIALytx
101 South Tryon St
Suite 2700
Charlotte, NC 28280
704.458.4798

**Comment by jparish3** [comment]
After further testing, the issue was related to source-data vs. source with geojson-source. It appears to be working with that combination. 
Does on-mapbox-layer-click work with pushing features to paper-dialog ?

**Comment by eterna2** [comment]
Hi wrote a better demo on the various way to load GeoJSON into `mapbox-gl-layer`.

You can see the source codes and demo [here](https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/mapbox-source-data.html).

Essentially, there are 2 way to 3 ways to load data. 

1. `source-data` for the `mapbox-layer`: this is a ease-of-use feature for static once off data. You cannot update this.

2. `source-url` for `geojson-source`: this load the data from a url. You can change the url at any point.

3. `source-data` for `geojson-source`: You can specify the GeoJSON directly. You can also change the data dynamically. However, you will need to ensure that you [notify Polymer of these changes](https://www.polymer-project.org/2.0/docs/devguide/model-data#notifysplices). An easy way is just to create a new Object, instead of mutating the features inside.

**Comment by eterna2** [comment]
As for pushing the features to paper-dialog:

yes and no. I did not create an attribute for u to directly data-bind because of the multiple possibilities. 

Instead, i dispatch `events`, which you can then use to update the variables you have binded to `paper-dialog`.

You can look at an example of a mousemove and mouseleave event to both change the render style as well as print the feature name.

[demo here](https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/event-handling.html)

**Comment by jparish3** [comment]
Thanks. That is very helpful. Is it possible to push multiple features from the geojson? 
Also, I encountered the error below with the data-driven style demo under<mapbox-gl> Should they be set up as a property?

Error: layers.country.paint.fill-color: "fill-color" does not support interpolation syntax
Use an identity property function instead: `{ "type": "identity", "property": "property: 'type', type: 'categorical', stops: [['Africa', '#FAA'], ['Asia', '#AAF']]"` }`

**Comment by eterna2** [comment]
Hi, 
I have added this plugin for the latest release (v2.0.9). 

doc:
https://www.webcomponents.org/element/PolymerVis/mapbox-gl/elements/mapbox-gl-geocoder

demo:
https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/geocoder.html

**Comment by eterna2** [comment]
Hi @jparish3 

I made a mistake in the example. U cannot place the string directly into the attribute.
Instead you need to define it as an `JSON obj`, and bind it to the attribute. Because by default, the attribute is expecting a `String`.

It will not know whether to accept a `String` or a `Function object`.

The correct example shld be
```html
 <mapbox-gl id="map"
    interactive
    map="{{map}}"
    map-style="mapbox://styles/mapbox/dark-v9"
    access-token="<MAPBOX_ACCESS_TOKEN>"
    latitude=40.66995747013945
    longitude=-103.59179687498357
    zoom=3></mapbox-gl>

  <mapbox-layer
    map="[[map]]"
    layer-id="country"
    rendering-type="fill"
    source="geojsonsrc"
    color="[[color]]"
    filter="[[filter"></mapbox-layer>

  <geojson-source
    map="[[map]]"
    source-id="geojsonsrc"
    source-url="https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_110m_admin_0_countries.geojson"></geojson-source>

```

js
```js
color = {property: 'continent', type: 'categorical', stops: [['Africa', '#FAA'], ['Asia', '#AAF']]}
filter = ['in', 'continent', 'Africa', 'Asia']
```
