### ISSUE TITLE
eventsToWatch 

### ISSUE THREAD

**Issue by jparish3** [PolymerVis/mapbox-gl#2]
I get 2 errors (below) when including events-to-watch="mapbox-gl-move". This was applied from the documentation, but the wording is unclear: A string with space delimited (map events)[https://www.mapbox.com/mapbox-gl-js/api/#Map] to listen to. The corresponding event with be prefix with mapbox-gl- e.g. move will result with mapbox-gl-move event to be fired.

Ultimately, I am trying to use the MapBoxZoomEvent to get the new bounds from ZoomBounds (LngLatBounds), but cannot get past this step.

Errors:
Uncaught TypeError: Cannot read property 'trim' of undefined
Uncaught ReferenceError: mapboxgl is not defined

**Comment by eterna2** [comment]
Sorry for the 2 bugs. For the 1st one, I forgot to check if the old string (for events to watch) exists or otherwise. The 2nd error is because I forgot to ensure mapbox-gl is loaded before watching the events.

I have also updated `eventstowatch` with some examples.

However, you u have misunderstood the mapbox events. 

`MapBoxZoomEvent` is the data type. You should listen to `boxzoomstart`, `boxzoomcancel`, or `boxzoomend` instead. https://www.mapbox.com/mapbox-gl-js/api/#map.event:boxzoomend

And note that boxzoom != zoom. Boxzoom is the zoom when you hold shift and select a box to zoom to. 

As for the center lat-lon, it is already binded to the attributes `latitude`, `longitude` by default.
