### ISSUE TITLE
on-mousemove change pointer and faster reaction?

### ISSUE THREAD

**Issue by ralexrdz** [PolymerVis/mapbox-gl#25]
the event looks like it takes around a second to trigger. Is there a way to make it shorter?

Also i'm trying to change the cursor when I'm over a layer without success

i've tried adding a class with css cursor property to `<mapbox-gl ..>` and `<mapbox-layer ..>`, but didn't work

**Comment by ralexrdz** [comment]
...

**Comment by eterna2** [comment]
I gave it a debounce to avoid event spams. I can expose an attribute to set the debounce time.

**Comment by eterna2** [comment]
@ralexrdz 
You can look at https://www.webcomponents.org/element/PolymerVis/mapbox-gl/demo/demo/event-handling.html

For as an example on how to change the cursor when over a layer. Ur css does not work because the mapbox default style in the shadowDom overwrites your light-dom css.

I have expose a CSS mixin for u to style the canvas element. 

As for the event trigger delay, I have no idea. I need an example to investigate, as u can see the demo does not have any delay.

**Comment by ralexrdz** [comment]
Thanks a lot! Really helps!
