### ISSUE TITLE
open popup click of marker

### ISSUE THREAD

**Issue by hirenpatel868** [PolymerVis/mapbox-gl#41]
want to open popup with some data on click of marker .....any method or sample avilable??

**Comment by eterna2** [comment]
@hirenpatel868 

`v2.1.2` of `mapbox-gl` adds a new component `mapbox-gl-popup`.

You can look at http://bl.ocks.org/eterna2/aa4787cae0515a7f5bc190c299bfb256 to see an example on how to use it.

The webcomponent.org page is currently broken due to https://github.com/Polymer/tools/issues/330 , so you can't see the API docs and demos.

See also #45 for more details
