### ISSUE TITLE
Add support for popups as polymer elements

### ISSUE THREAD

**Issue by PapeCoding** [PolymerVis/mapbox-gl#45]
Can you add a polymer element recreating the popups? Without it is is hardly possible to use HTML with CSS in the popups

**Comment by eterna2** [comment]
Hi @PapeCoding 

`v2.1.2` of `mapbox-gl` adds a new component `mapbox-gl-popup`.

You can look at http://bl.ocks.org/eterna2/aa4787cae0515a7f5bc190c299bfb256 to see an example on how to use it.

The webcomponent.org page is currently broken due to https://github.com/Polymer/tools/issues/330 , so you can't see the API docs and demos.

**Comment by eterna2** [comment]
@PapeCoding 
Just an added note. Because the way webcomponents uses the shadowDOM, and mapbox-gl attaching the slotted element onto the map, u cannot style it the normal way in CSS in the lightDOM.

There are 2 workarounds:
- inline styling of the slotted popup element (slot="popup-content")
- make the slotted popup element (slot="popup-content") as a custom element (with the style embedded inside)

**Comment by PapeCoding** [comment]
Thank you for your work!
Unfortunately it is not possible to create popups together with their markers within a dom-repeat. Am i doing something wrong?
